name: ftir311
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - umap-learn
  - pynndescent
  - matplotlib
  - plotly
  - imbalanced-learn
  - xgboost
  - shap
  - statsmodels
  - openpyxl         # <— добавили для чтения .xlsx
  - pyyaml
  - hydra-core
  - mlflow
  - ipykernel
  - ipywidgets
  - rich
  - tqdm
  - dvc
  - pre-commit
  - black
  - isort
  - flake8
  - pip              # <— чтобы при пересборке можно было использовать pip-пакеты (при необходимости)
